config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  get 'about' => 'pages#about'

  root 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  validates :description, presence: true
  validates :user_id, presence: true


  belongs_to :user
  has_attached_file :image, styles: { thumb: '100x100', small: '300x300', medium: '600x600>', big: '1000x1000>' }


  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/,
                                    size: { less_than: 5.megabytes }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable,
          :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?

  protected

  def configure_devise_permitted_parameters
    registration_params = [:name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) {
          |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) {
          |u| u.permit(registration_params)
      }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show]
  before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order('created_at desc')
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])

    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
               concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
                        concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
                        concat content_tag(:span, 'Close', class: 'sr-only')
                      end)
               concat message
             end)
    end
    nil
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
  <head>
    <title>PhotoShare</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'partials/header' %>

    <div class="container">
      <%= flash_messages %>
    </div>

    <%= yield %>

    <%= render 'partials/footer' %>
  </body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in? %>

<% else %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome to PhotoShare!</h1>
      <p>
        Store your photos and creative ideas. Share them with others!
      </p>
      <p>
        <%= link_to 'Sign Up Now!', new_user_registration_path, class: 'btn btn-success btn-lg' %>
      </p>
    </div>
  </div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  <%= link_to 'PhotoShare', root_path %> is a sample application created with
  <%= link_to 'Ruby on Rails', 'http://rubyonrails.org' %> framework.
</p>

app/views/partials/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p><strong>This form contains <%= pluralize(object.errors.count, 'errors') %>.</strong></p>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">
      PhotoShare by Aris Liberopoulos
    </p>
  </div>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'PhotoShare', root_path, class: 'navbar-brand'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Add <i class= "fa fa-plus-circle fa-lg" data-toggle="tooltip" data-placement="top" title="New"></i>'.html_safe, new_pin_path %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to '<i class= "fa fa-sign-out fa-lg" data-toggle="tooltip" data-placement="top" title="Logout"></i>'.html_safe, destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/pins/_form.html.erb
<%= form_for(@pin) do |f| %>
  <%= render 'partials/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label 'Upload an image' %>
    <%= f.file_field :image %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control input-lg' %>
  </div>
  <div class="row">&nbsp;</div>
  <div class="row">&nbsp;</div>
  <div class="row">
    <div class="col-xs-offset-3 col-xs-6">
      <div class="form-group text-center">
        <%= f.submit class: 'btn btn-success btn-block' %>
      </div>
    </div>
  </div>

<% end %>

app/views/pins/_pin.html.erb
<div class="box panel panel-default">
  <%= link_to (image_tag pin.image.url), pin %>
  <div class="panel-body">
    <p>
      <%= pin.description %>
    </p>
    <p>
      <strong>
        Posted by <%= pin.user.name %>
      </strong>
    </p>

    <% if current_user == pin.user %>
      <p>
        <%= link_to '<i class= "fa fa-pencil" data-toggle="tooltip" data-placement="top" title="Edit"></i>'.html_safe, edit_pin_path(pin) %> |
        <%= link_to '<i class= "fa fa-trash-o" data-toggle="tooltip" data-placement="top" title="Delete"></i>'.html_safe, pin, method: :delete, data: { confirm: 'Are you sure?' } %>
      </p>
    <% end %>
    </div>
</div>

app/views/pins/edit.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-sm-6">Editing Pin</h1>
  </div>
  <div class="row">&nbsp;</div>
  <div class="row">&nbsp;</div>
  <div class="row">
    <div class="form col-sm-6">

      <%= render 'form' %>

      <%= link_to 'Show', @pin %> |
      <%= link_to 'Back', pins_path %>
    </div>
  </div>
</div>

app/views/pins/index.html.erb
<%= render 'pages/home' %>
<div class="container transitions-enabled centered masonry masonry-brick" id="pins">
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-sm-6">New Pin</h1>
  </div>
  <div class="row">&nbsp;</div>
  <div class="row">&nbsp;</div>
  <div class="row">
    <div class="form col-sm-6">

      <%= render 'form' %>

      <%= link_to 'Back', pins_path %>
    </div>
  </div>
</div>

app/views/pins/show.html.erb
<div class="container">
  <div class="row" id="pin_show">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="panel panel-default">
        <div class="panel-heading pin_image">
          <%= image_tag @pin.image.url%>
        </div>
        <div class="panel-body">
          <p class="description">
            <%= @pin.description %>
          </p>
        </div>
        <div class="panel-footer">
          <div class="row">
            <div class="col-sm-6">
              <p class="user">
                <strong>
                  Posted by <%= @pin.user.name %>
                </strong>
              </p>
            </div>
            <div class="col-sm-6">
              <div class="btn-group pull-right">
                <% if current_user == @pin.user %>
                  <%= link_to 'Edit', edit_pin_path(@pin), class: 'btn btn-default' %>
                <% end %>
                <%= link_to 'Back', pins_path, class: 'btn btn-default' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>